#!/usr/bin/env python3
"""
STUD.io — Seed Generator

Reads CSV files from csv/ and generates SQL seed files in sql/seeds/.
Safe to re-run — seed files are fully regenerated each time.

Usage:
    python generate_seeds.py
"""

import csv
from pathlib import Path

CSV_DIR  = Path(__file__).parent / "csv"
SEED_DIR = Path(__file__).parent / "sql" / "seeds"


def clean(val):
    if val is None:
        return None
    v = str(val).strip()
    return v if v else None


def escape(val):
    """Escape a value for SQL insertion."""
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def escape_array(val, cast):
    """Escape a comma-separated value as a PostgreSQL array literal."""
    if not val:
        return f"NULL::{cast}[]"
    # Strip outer curly braces if already present in the CSV value
    val = val.strip().lstrip("{").rstrip("}")
    elements = [v.strip() for v in val.split(",") if v.strip()]
    return "'{" + ",".join(elements) + "}'::" + cast + "[]"


def log(msg):
    print(f"  {msg}")


def seed_header(table, csv_file):
    return [
        "-- =============================================================================",
        f"-- Seed: {table}",
        "-- Generated by generate_seeds.py — do not edit directly",
        f"-- Edit csv/{csv_file} instead",
        "-- =============================================================================",
        "",
    ]


def tool_row(table, id_col, id_val, brand_id, name, version,
             tool_types, plugin_formats, description, workflow_notes, tags):
    return (
        f"INSERT INTO {table}"
        f" ({id_col}, brand_id, name, version, tool_types, plugin_formats, description, workflow_notes, tags)"
        f" VALUES ("
        f"{escape(id_val)}, "
        f"{escape(brand_id) if brand_id else 'NULL'}, "
        f"{escape(name)}, "
        f"{escape(version)}, "
        f"{escape_array(tool_types, 'tool_type')}, "
        f"{escape_array(plugin_formats, 'plugin_format')}, "
        f"{escape(description)}, "
        f"{escape(workflow_notes)}, "
        f"{escape_array(tags, 'tag_type')}"
        f") ON CONFLICT ({id_col}) DO UPDATE SET"
        f" version = EXCLUDED.version,"
        f" description = EXCLUDED.description,"
        f" workflow_notes = EXCLUDED.workflow_notes,"
        f" updated_at = NOW();"
    )


def read_tool_csv(src, id_col):
    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            name = clean(row.get("name"))
            if not name:
                continue
            rows.append((
                clean(row.get(id_col)),
                clean(row.get("brand_id")),
                name,
                clean(row.get("version")),
                clean(row.get("tool_types")),
                clean(row.get("plugin_formats")),
                clean(row.get("description")),
                clean(row.get("workflow_notes")),
                clean(row.get("tags")),
            ))
    return rows


# ---------------------------------------------------------------------------
# Brands
# ---------------------------------------------------------------------------
def generate_brands():
    src  = CSV_DIR / "brands.csv"
    dest = SEED_DIR / "01_brands.sql"

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            brand_id    = clean(row.get("brand_id"))
            name        = clean(row.get("name"))
            common_name = clean(row.get("common_name"))
            entity_type = clean(row.get("entity_type")) or "Manufacturer"
            website     = clean(row.get("website"))
            if not name:
                continue
            rows.append((brand_id, name, common_name, entity_type, website))

    lines = seed_header("brands", "brands.csv")

    for brand_id, name, common_name, entity_type, website in rows:
        lines.append(
            f"INSERT INTO brands (brand_id, name, common_name, entity_type, website)"
            f" VALUES ({escape(brand_id)}, {escape(name)}, {escape(common_name)}, {escape(entity_type)}, {escape(website)})"
            f" ON CONFLICT (brand_id) DO UPDATE SET"
            f" website = EXCLUDED.website,"
            f" entity_type = EXCLUDED.entity_type,"
            f" updated_at = NOW();"
            f"  -- common_name intentionally not updated (manually maintained)"
        )

    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} brands → {dest.name}")


# ---------------------------------------------------------------------------
# Workstations
# ---------------------------------------------------------------------------
def generate_workstations():
    src  = CSV_DIR / "workstations.csv"
    dest = SEED_DIR / "02_workstations.sql"
    rows = read_tool_csv(src, "workstation_id")
    lines = seed_header("workstations", "workstations.csv")
    for r in rows:
        lines.append(tool_row("workstations", "workstation_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} workstations → {dest.name}")


# ---------------------------------------------------------------------------
# Workflow Tools
# ---------------------------------------------------------------------------
def generate_workflow_tools():
    src  = CSV_DIR / "workflow_tools.csv"
    dest = SEED_DIR / "03_workflow_tools.sql"
    rows = read_tool_csv(src, "workflow_tool_id")
    lines = seed_header("workflow_tools", "workflow_tools.csv")
    for r in rows:
        lines.append(tool_row("workflow_tools", "workflow_tool_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} workflow tools → {dest.name}")


# ---------------------------------------------------------------------------
# Measurement Tools
# ---------------------------------------------------------------------------
def generate_measurement_tools():
    src  = CSV_DIR / "measurement_tools.csv"
    dest = SEED_DIR / "04_measurement_tools.sql"
    rows = read_tool_csv(src, "measurement_tool_id")
    lines = seed_header("measurement_tools", "measurement_tools.csv")
    for r in rows:
        lines.append(tool_row("measurement_tools", "measurement_tool_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} measurement tools → {dest.name}")


# ---------------------------------------------------------------------------
# Reference Tools
# ---------------------------------------------------------------------------
def generate_reference_tools():
    src  = CSV_DIR / "reference_tools.csv"
    dest = SEED_DIR / "05_reference_tools.sql"

    if not src.exists():
        log("reference_tools.csv not found — skipping")
        return

    rows = read_tool_csv(src, "reference_tool_id")
    lines = seed_header("reference_tools", "reference_tools.csv")
    for r in rows:
        lines.append(tool_row("reference_tools", "reference_tool_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} reference tools → {dest.name}")


# ---------------------------------------------------------------------------
# Composition Tools
# ---------------------------------------------------------------------------
def generate_composition_tools():
    src  = CSV_DIR / "composition_tools.csv"
    dest = SEED_DIR / "06_composition_tools.sql"
    rows = read_tool_csv(src, "composition_tool_id")
    lines = seed_header("composition_tools", "composition_tools.csv")
    for r in rows:
        lines.append(tool_row("composition_tools", "composition_tool_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} composition tools → {dest.name}")


# ---------------------------------------------------------------------------
# Admin Tools
# ---------------------------------------------------------------------------
def generate_admin_tools():
    src  = CSV_DIR / "admin_tools.csv"
    dest = SEED_DIR / "07_admin_tools.sql"
    rows = read_tool_csv(src, "admin_tool_id")
    lines = seed_header("admin_tools", "admin_tools.csv")
    for r in rows:
        lines.append(tool_row("admin_tools", "admin_tool_id", *r))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} admin tools → {dest.name}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("  STUD.io — Seed Generator")
    print("=" * 60)

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    for f in SEED_DIR.glob("*.sql"):
        f.unlink()

    generate_brands()
    generate_workstations()
    generate_workflow_tools()
    generate_measurement_tools()
    generate_reference_tools()
    generate_composition_tools()
    generate_admin_tools()

    print("\n" + "=" * 60)
    print("  Seed files written to sql/seeds/")
    print("=" * 60)


if __name__ == "__main__":
    main()
