#!/usr/bin/env python3
"""
STUD.io — Seed Generator

Reads CSV files from csv/ and generates SQL seed files in sql/seeds/.
Safe to re-run — seed files are fully regenerated each time.

Usage:
    python generate_seeds.py
"""

import csv
from pathlib import Path

CSV_DIR  = Path(__file__).parent.parent / "csv"
SEED_DIR = Path(__file__).parent.parent / "sql" / "seeds"


def clean(val):
    if val is None:
        return None
    v = str(val).strip()
    return v if v else None


def escape(val):
    """Escape a value for SQL insertion."""
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def escape_array(val, cast):
    """Escape a comma-separated value as a PostgreSQL array literal."""
    if not val:
        return f"NULL::{cast}[]"
    # Strip outer curly braces if already present in the CSV value
    val = val.strip().lstrip("{").rstrip("}")
    elements = [v.strip() for v in val.split(",") if v.strip()]
    return "'{" + ",".join(elements) + "}'::" + cast + "[]"


def log(msg):
    print(f"  {msg}")


def seed_header(table, csv_file):
    return [
        "-- =============================================================================",
        f"-- Seed: {table}",
        "-- Generated by generate_seeds.py — do not edit directly",
        f"-- Edit csv/{csv_file} instead",
        "-- =============================================================================",
        "",
    ]


# ---------------------------------------------------------------------------
# Map builders
# ---------------------------------------------------------------------------
def _build_type_map(csv_name):
    """Return type_name.lower() → type_id from the given CSV file."""
    src = CSV_DIR / csv_name
    m = {}
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            name = (row.get("type_name") or "").strip()
            tid  = (row.get("type_id")   or "").strip()
            if name and tid:
                m[name.lower()] = tid
    return m


def build_tool_type_map():
    """Return type_name.lower() → type_id from csv/tool_types.csv."""
    return _build_type_map("tool_types.csv")


def build_entity_type_map():
    """Return type_name.lower() → type_id from csv/entity_types.csv."""
    return _build_type_map("entity_types.csv")


def build_plugin_format_map():
    """Return type_name.lower() → type_id from csv/plugin_formats.csv."""
    return _build_type_map("plugin_formats.csv")


def build_tag_type_map():
    """Return type_name.lower() → type_id from csv/tag_types.csv."""
    return _build_type_map("tag_types.csv")


def build_model_type_map():
    """Return type_name.lower() → type_id from csv/model_types.csv."""
    return _build_type_map("model_types.csv")


def build_effect_type_map():
    """Return type_name.lower() → type_id from csv/effect_types.csv."""
    return _build_type_map("effect_types.csv")


def build_instrument_type_map():
    """Return type_name.lower() → type_id from csv/instrument_types.csv."""
    return _build_type_map("instrument_types.csv")


# ---------------------------------------------------------------------------
# Resolvers
# ---------------------------------------------------------------------------
def _resolve_uuid_array(names_str, type_map):
    """Resolve a comma-separated string of type names to a UUID array SQL literal."""
    if not names_str:
        return "NULL::uuid[]"
    ids = []
    for name in names_str.split(","):
        name = name.strip()
        tid  = type_map.get(name.lower())
        if tid:
            ids.append(tid)
    if not ids:
        return "NULL::uuid[]"
    return "'{" + ",".join(ids) + "}'::uuid[]"


def resolve_tool_type_ids(tool_types_str, tool_type_map):
    """Resolve comma-separated type names to a UUID array SQL literal."""
    return _resolve_uuid_array(tool_types_str, tool_type_map)


def resolve_entity_type_id(entity_type_str, entity_type_map):
    """Resolve a single entity type name to a UUID SQL literal or NULL."""
    if not entity_type_str:
        return "NULL"
    tid = entity_type_map.get(entity_type_str.strip().lower())
    if not tid:
        return "NULL"
    return escape(tid)


def resolve_plugin_format_ids(plugin_formats_str, plugin_format_map):
    """Resolve comma-separated plugin format names to a UUID array SQL literal."""
    return _resolve_uuid_array(plugin_formats_str, plugin_format_map)


def resolve_tag_ids(tags_str, tag_map):
    """Resolve comma-separated tag names to a UUID array SQL literal."""
    return _resolve_uuid_array(tags_str, tag_map)


def resolve_model_type_ids(model_types_str, model_type_map):
    """Resolve comma-separated model type names to a UUID array SQL literal."""
    return _resolve_uuid_array(model_types_str, model_type_map)


def resolve_effect_type_ids(effect_types_str, effect_type_map):
    """Resolve comma-separated effect type names to a UUID array SQL literal."""
    return _resolve_uuid_array(effect_types_str, effect_type_map)


def resolve_instrument_type_ids(instrument_types_str, instrument_type_map):
    """Resolve comma-separated instrument type names to a UUID array SQL literal."""
    return _resolve_uuid_array(instrument_types_str, instrument_type_map)


# ---------------------------------------------------------------------------
# Generic lookup table seed generator
# ---------------------------------------------------------------------------
def _generate_lookup_table(table_name, csv_name, dest_name):
    src  = CSV_DIR / csv_name
    dest = SEED_DIR / dest_name
    lines = seed_header(table_name, csv_name)
    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            type_id   = (row.get("type_id")          or "").strip()
            type_name = (row.get("type_name")         or "").strip()
            type_desc = (row.get("type_description")  or "").strip() or None
            if type_id and type_name:
                rows.append((type_id, type_name, type_desc))
    for type_id, type_name, type_desc in rows:
        lines.append(
            f"INSERT INTO {table_name} (type_id, type_name, type_description)"
            f" VALUES ({escape(type_id)}, {escape(type_name)}, {escape(type_desc)})"
            f" ON CONFLICT (type_id) DO UPDATE SET"
            f" type_name = EXCLUDED.type_name,"
            f" type_description = EXCLUDED.type_description;"
        )
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} {table_name} → {dest.name}")


def generate_entity_types():
    _generate_lookup_table("entity_types", "entity_types.csv", "01_entity_types.sql")


def generate_tag_types():
    _generate_lookup_table("tag_types", "tag_types.csv", "02_tag_types.sql")


def generate_plugin_formats():
    _generate_lookup_table("plugin_formats", "plugin_formats.csv", "03_plugin_formats.sql")


def generate_effect_types():
    _generate_lookup_table("effect_types", "effect_types.csv", "04_effect_types.sql")


def generate_instrument_types():
    _generate_lookup_table("instrument_types", "instrument_types.csv", "05_instrument_types.sql")


def generate_model_types():
    _generate_lookup_table("model_types", "model_types.csv", "06_model_types.sql")


def generate_tool_types():
    _generate_lookup_table("tool_types", "tool_types.csv", "07_tool_types.sql")


def tool_row(table, id_col, id_val, brand_id, tool_name, version,
             tool_types, plugin_formats, description, workflow_notes, tags,
             tool_type_map, plugin_format_map, tag_map):
    return (
        f"INSERT INTO {table}"
        f" ({id_col}, brand_id, tool_name, version, tool_type_ids, plugin_format_ids, description, workflow_notes, tag_ids)"
        f" VALUES ("
        f"{escape(id_val)}, "
        f"{escape(brand_id) if brand_id else 'NULL'}, "
        f"{escape(tool_name)}, "
        f"{escape(version)}, "
        f"{resolve_tool_type_ids(tool_types, tool_type_map)}, "
        f"{resolve_plugin_format_ids(plugin_formats, plugin_format_map)}, "
        f"{escape(description)}, "
        f"{escape(workflow_notes)}, "
        f"{resolve_tag_ids(tags, tag_map)}"
        f") ON CONFLICT ({id_col}) DO UPDATE SET"
        f" version = EXCLUDED.version,"
        f" tool_type_ids = EXCLUDED.tool_type_ids,"
        f" description = EXCLUDED.description,"
        f" workflow_notes = EXCLUDED.workflow_notes,"
        f" updated_at = NOW();"
    )


def read_tool_csv(src, id_col):
    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            tool_name = clean(row.get("tool_name"))
            if not tool_name:
                continue
            rows.append((
                clean(row.get(id_col)),
                clean(row.get("brand_id")),
                tool_name,
                clean(row.get("version")),
                clean(row.get("tool_types")),
                clean(row.get("plugin_formats")),
                clean(row.get("description")),
                clean(row.get("workflow_notes")),
                clean(row.get("tags")),
            ))
    return rows


# ---------------------------------------------------------------------------
# Brands
# ---------------------------------------------------------------------------
def generate_brands(entity_type_map):
    src  = CSV_DIR / "brands.csv"
    dest = SEED_DIR / "08_brands.sql"

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            brand_id    = clean(row.get("brand_id"))
            legal_name  = clean(row.get("legal_name"))
            brand_name  = clean(row.get("brand_name"))
            entity_type = clean(row.get("entity_type")) or "Manufacturer"
            website     = clean(row.get("website"))
            description = clean(row.get("description"))
            founder     = clean(row.get("founder"))
            years       = clean(row.get("years"))
            if not legal_name:
                continue
            rows.append((brand_id, legal_name, brand_name, entity_type, website, description, founder, years))

    lines = seed_header("brands", "brands.csv")

    for brand_id, legal_name, brand_name, entity_type, website, description, founder, years in rows:
        lines.append(
            f"INSERT INTO brands (brand_id, legal_name, brand_name, entity_type_id, website, description, founder, years)"
            f" VALUES ({escape(brand_id)}, {escape(legal_name)}, {escape(brand_name)}, {resolve_entity_type_id(entity_type, entity_type_map)}, {escape(website)}, {escape(description)}, {escape(founder)}, {escape(years)})"
            f" ON CONFLICT (brand_id) DO UPDATE SET"
            f" website = EXCLUDED.website,"
            f" entity_type_id = EXCLUDED.entity_type_id,"
            f" description = EXCLUDED.description,"
            f" founder = EXCLUDED.founder,"
            f" years = EXCLUDED.years,"
            f" updated_at = NOW();"
            f"  -- brand_name intentionally not updated (manually maintained)"
        )

    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} brands → {dest.name}")


# ---------------------------------------------------------------------------
# Workstations
# ---------------------------------------------------------------------------
def generate_workstations(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "workstations.csv"
    dest = SEED_DIR / "10_workstations.sql"
    rows = read_tool_csv(src, "workstation_id")
    lines = seed_header("workstations", "workstations.csv")
    for r in rows:
        lines.append(tool_row("workstations", "workstation_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} workstations → {dest.name}")


# ---------------------------------------------------------------------------
# Workflow Tools
# ---------------------------------------------------------------------------
def generate_workflow_tools(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "workflow_tools.csv"
    dest = SEED_DIR / "11_workflow_tools.sql"
    rows = read_tool_csv(src, "workflow_tool_id")
    lines = seed_header("workflow_tools", "workflow_tools.csv")
    for r in rows:
        lines.append(tool_row("workflow_tools", "workflow_tool_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} workflow tools → {dest.name}")


# ---------------------------------------------------------------------------
# Measurement Tools
# ---------------------------------------------------------------------------
def generate_measurement_tools(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "measurement_tools.csv"
    dest = SEED_DIR / "12_measurement_tools.sql"
    rows = read_tool_csv(src, "measurement_tool_id")
    lines = seed_header("measurement_tools", "measurement_tools.csv")
    for r in rows:
        lines.append(tool_row("measurement_tools", "measurement_tool_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} measurement tools → {dest.name}")


# ---------------------------------------------------------------------------
# Reference Tools
# ---------------------------------------------------------------------------
def generate_reference_tools(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "reference_tools.csv"
    dest = SEED_DIR / "13_reference_tools.sql"

    if not src.exists():
        log("reference_tools.csv not found — skipping")
        return

    rows = read_tool_csv(src, "reference_tool_id")
    lines = seed_header("reference_tools", "reference_tools.csv")
    for r in rows:
        lines.append(tool_row("reference_tools", "reference_tool_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} reference tools → {dest.name}")


# ---------------------------------------------------------------------------
# Composition Tools
# ---------------------------------------------------------------------------
def generate_composition_tools(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "composition_tools.csv"
    dest = SEED_DIR / "14_composition_tools.sql"
    rows = read_tool_csv(src, "composition_tool_id")
    lines = seed_header("composition_tools", "composition_tools.csv")
    for r in rows:
        lines.append(tool_row("composition_tools", "composition_tool_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} composition tools → {dest.name}")


# ---------------------------------------------------------------------------
# Admin Tools
# ---------------------------------------------------------------------------
def generate_admin_tools(tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "admin_tools.csv"
    dest = SEED_DIR / "15_admin_tools.sql"
    rows = read_tool_csv(src, "admin_tool_id")
    lines = seed_header("admin_tools", "admin_tools.csv")
    for r in rows:
        lines.append(tool_row("admin_tools", "admin_tool_id", *r,
                              tool_type_map=tool_type_map,
                              plugin_format_map=plugin_format_map,
                              tag_map=tag_map))
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} admin tools → {dest.name}")


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
def generate_models(model_type_map):
    src  = CSV_DIR / "models.csv"
    dest = SEED_DIR / "09_models.sql"

    if not src.exists():
        log("models.csv not found — run convert_models.py first, then re-run")
        return

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            model_name = clean(row.get("model_name"))
            if not model_name:
                continue
            rows.append((
                clean(row.get("model_id")),
                clean(row.get("brand_id")),
                model_name,
                clean(row.get("model_types")),
                clean(row.get("creator")),
                clean(row.get("years_active")),
                clean(row.get("links")),
                clean(row.get("description")),
                clean(row.get("recording_notes")),
                clean(row.get("artist_reference")),
                clean(row.get("attributes")),
            ))

    lines = seed_header("models", "models.csv")
    for (model_id, brand_id, model_name, model_types, creator,
         years_active, links, description, recording_notes, artist_reference,
         attributes) in rows:
        attrs_sql = escape(attributes) + "::jsonb" if attributes else "NULL::jsonb"
        lines.append(
            f"INSERT INTO models"
            f" (model_id, brand_id, model_name, model_type_ids, creator, years_active,"
            f" links, description, recording_notes, artist_reference, attributes)"
            f" VALUES ("
            f"{escape(model_id)}, "
            f"{escape(brand_id) if brand_id else 'NULL'}, "
            f"{escape(model_name)}, "
            f"{resolve_model_type_ids(model_types, model_type_map)}, "
            f"{escape(creator)}, "
            f"{escape(years_active)}, "
            f"{escape(links)}, "
            f"{escape(description)}, "
            f"{escape(recording_notes)}, "
            f"{escape(artist_reference)}, "
            f"{attrs_sql}"
            f") ON CONFLICT (model_id) DO UPDATE SET"
            f" model_type_ids = EXCLUDED.model_type_ids,"
            f" creator = EXCLUDED.creator,"
            f" years_active = EXCLUDED.years_active,"
            f" description = EXCLUDED.description,"
            f" recording_notes = EXCLUDED.recording_notes,"
            f" artist_reference = EXCLUDED.artist_reference,"
            f" attributes = EXCLUDED.attributes,"
            f" updated_at = NOW();"
        )
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} models → {dest.name}")


# ---------------------------------------------------------------------------
# Effects
# ---------------------------------------------------------------------------
def generate_effects(tool_type_map, effect_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "effects.csv"
    dest = SEED_DIR / "16_effects.sql"

    if not src.exists():
        log("effects.csv not found — run convert_effects.py first, then re-run")
        return

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            effect_name = clean(row.get("effect_name"))
            if not effect_name:
                continue
            rows.append((
                clean(row.get("effect_id")),
                clean(row.get("brand_id")),
                clean(row.get("model_ids")),
                effect_name,
                clean(row.get("version")),
                clean(row.get("collection")),
                clean(row.get("effect_types")),
                clean(row.get("tool_types")),
                clean(row.get("plugin_formats")),
                clean(row.get("description")),
                clean(row.get("workflow_notes")),
                clean(row.get("recording_notes")),
                clean(row.get("artist_reference")),
                clean(row.get("attributes")),
                clean(row.get("tags")),
            ))

    lines = seed_header("effects", "effects.csv")
    for (effect_id, brand_id, model_ids, effect_name, version,
         collection, effect_types, tool_types, plugin_formats,
         description, workflow_notes, recording_notes, artist_reference,
         attributes, tags) in rows:
        attrs_sql = escape(attributes) + "::jsonb" if attributes else "NULL::jsonb"
        lines.append(
            f"INSERT INTO effects"
            f" (effect_id, brand_id, model_ids, effect_name, version, collection, effect_type_ids,"
            f" tool_type_ids, plugin_format_ids, description, workflow_notes,"
            f" recording_notes, artist_reference, attributes, tag_ids)"
            f" VALUES ("
            f"{escape(effect_id)}, "
            f"{escape(brand_id) if brand_id else 'NULL'}, "
            f"{escape_array(model_ids, 'uuid')}, "
            f"{escape(effect_name)}, "
            f"{escape(version)}, "
            f"{escape(collection)}, "
            f"{resolve_effect_type_ids(effect_types, effect_type_map)}, "
            f"{resolve_tool_type_ids(tool_types, tool_type_map)}, "
            f"{resolve_plugin_format_ids(plugin_formats, plugin_format_map)}, "
            f"{escape(description)}, "
            f"{escape(workflow_notes)}, "
            f"{escape(recording_notes)}, "
            f"{escape(artist_reference)}, "
            f"{attrs_sql}, "
            f"{resolve_tag_ids(tags, tag_map)}"
            f") ON CONFLICT (effect_id) DO UPDATE SET"
            f" brand_id = EXCLUDED.brand_id,"
            f" model_ids = EXCLUDED.model_ids,"
            f" effect_name = EXCLUDED.effect_name,"
            f" version = EXCLUDED.version,"
            f" collection = EXCLUDED.collection,"
            f" effect_type_ids = EXCLUDED.effect_type_ids,"
            f" tool_type_ids = EXCLUDED.tool_type_ids,"
            f" plugin_format_ids = EXCLUDED.plugin_format_ids,"
            f" description = EXCLUDED.description,"
            f" workflow_notes = EXCLUDED.workflow_notes,"
            f" recording_notes = EXCLUDED.recording_notes,"
            f" artist_reference = EXCLUDED.artist_reference,"
            f" attributes = EXCLUDED.attributes,"
            f" tag_ids = EXCLUDED.tag_ids,"
            f" updated_at = NOW();"
        )
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} effects → {dest.name}")


# ---------------------------------------------------------------------------
# Instruments
# ---------------------------------------------------------------------------
def generate_instruments(instrument_type_map, tool_type_map, plugin_format_map, tag_map):
    src  = CSV_DIR / "instruments.csv"
    dest = SEED_DIR / "17_instruments.sql"

    if not src.exists():
        log("instruments.csv not found — run convert_instruments.py first, then re-run")
        return

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            instrument_name = clean(row.get("instrument_name"))
            if not instrument_name:
                continue
            rows.append((
                clean(row.get("instrument_id")),
                clean(row.get("brand_id")),
                clean(row.get("model_ids")),
                instrument_name,
                clean(row.get("version")),
                clean(row.get("instrument_types")),
                clean(row.get("tool_types")),
                clean(row.get("plugin_formats")),
                clean(row.get("description")),
                clean(row.get("instrument_notes")),
                clean(row.get("recording_notes")),
                clean(row.get("tags")),
                clean(row.get("attributes")),
            ))

    lines = seed_header("instruments", "instruments.csv")
    for (instrument_id, brand_id, model_ids, instrument_name, version,
         instrument_types, tool_types, plugin_formats,
         description, instrument_notes, recording_notes, tags, attributes) in rows:
        attrs_sql = escape(attributes) + "::jsonb" if attributes else "NULL::jsonb"
        lines.append(
            f"INSERT INTO instruments"
            f" (instrument_id, brand_id, model_ids, instrument_name, version, instrument_type_ids,"
            f" tool_type_ids, plugin_format_ids, description, instrument_notes,"
            f" recording_notes, tag_ids, attributes)"
            f" VALUES ("
            f"{escape(instrument_id)}, "
            f"{escape(brand_id) if brand_id else 'NULL'}, "
            f"{escape_array(model_ids, 'uuid')}, "
            f"{escape(instrument_name)}, "
            f"{escape(version)}, "
            f"{resolve_instrument_type_ids(instrument_types, instrument_type_map)}, "
            f"{resolve_tool_type_ids(tool_types, tool_type_map)}, "
            f"{resolve_plugin_format_ids(plugin_formats, plugin_format_map)}, "
            f"{escape(description)}, "
            f"{escape(instrument_notes)}, "
            f"{escape(recording_notes)}, "
            f"{resolve_tag_ids(tags, tag_map)}, "
            f"{attrs_sql}"
            f") ON CONFLICT (instrument_id) DO UPDATE SET"
            f" brand_id = EXCLUDED.brand_id,"
            f" model_ids = EXCLUDED.model_ids,"
            f" instrument_name = EXCLUDED.instrument_name,"
            f" version = EXCLUDED.version,"
            f" instrument_type_ids = EXCLUDED.instrument_type_ids,"
            f" tool_type_ids = EXCLUDED.tool_type_ids,"
            f" plugin_format_ids = EXCLUDED.plugin_format_ids,"
            f" description = EXCLUDED.description,"
            f" instrument_notes = EXCLUDED.instrument_notes,"
            f" recording_notes = EXCLUDED.recording_notes,"
            f" tag_ids = EXCLUDED.tag_ids,"
            f" attributes = EXCLUDED.attributes,"
            f" updated_at = NOW();"
        )
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} instruments → {dest.name}")


# ---------------------------------------------------------------------------
# Libraries
# ---------------------------------------------------------------------------
def generate_libraries(tag_map):
    src  = CSV_DIR / "libraries.csv"
    dest = SEED_DIR / "18_libraries.sql"

    if not src.exists():
        log("libraries.csv not found — run convert_libraries.py first, then re-run")
        return

    rows = []
    with open(src, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            library_name = clean(row.get("library_name"))
            if not library_name:
                continue
            rows.append((
                clean(row.get("library_id")),
                clean(row.get("brand_id")),
                clean(row.get("model_ids")),
                library_name,
                clean(row.get("description")),
                clean(row.get("instrument_notes")),
                clean(row.get("recording_notes")),
                clean(row.get("tags")),
                clean(row.get("attributes")),
            ))

    lines = seed_header("libraries", "libraries.csv")
    for (library_id, brand_id, model_ids, library_name,
         description, instrument_notes, recording_notes, tags, attributes) in rows:
        attrs_sql = escape(attributes) + "::jsonb" if attributes else "NULL::jsonb"
        lines.append(
            f"INSERT INTO libraries"
            f" (library_id, brand_id, model_ids, library_name, description,"
            f" instrument_notes, recording_notes, tag_ids, attributes)"
            f" VALUES ("
            f"{escape(library_id)}, "
            f"{escape(brand_id) if brand_id else 'NULL'}, "
            f"{escape_array(model_ids, 'uuid')}, "
            f"{escape(library_name)}, "
            f"{escape(description)}, "
            f"{escape(instrument_notes)}, "
            f"{escape(recording_notes)}, "
            f"{resolve_tag_ids(tags, tag_map)}, "
            f"{attrs_sql}"
            f") ON CONFLICT (library_id) DO UPDATE SET"
            f" brand_id = EXCLUDED.brand_id,"
            f" model_ids = EXCLUDED.model_ids,"
            f" library_name = EXCLUDED.library_name,"
            f" description = EXCLUDED.description,"
            f" instrument_notes = EXCLUDED.instrument_notes,"
            f" recording_notes = EXCLUDED.recording_notes,"
            f" tag_ids = EXCLUDED.tag_ids,"
            f" attributes = EXCLUDED.attributes,"
            f" updated_at = NOW();"
        )
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    log(f"{len(rows)} libraries → {dest.name}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("  STUD.io — Seed Generator")
    print("=" * 60)

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    for f in SEED_DIR.glob("*.sql"):
        f.unlink()

    entity_type_map    = build_entity_type_map()
    tag_map            = build_tag_type_map()
    plugin_format_map  = build_plugin_format_map()
    effect_type_map    = build_effect_type_map()
    instrument_type_map = build_instrument_type_map()
    model_type_map     = build_model_type_map()
    tool_type_map      = build_tool_type_map()

    generate_entity_types()
    generate_tag_types()
    generate_plugin_formats()
    generate_effect_types()
    generate_instrument_types()
    generate_model_types()
    generate_tool_types()
    generate_brands(entity_type_map)
    generate_models(model_type_map)
    generate_workstations(tool_type_map, plugin_format_map, tag_map)
    generate_workflow_tools(tool_type_map, plugin_format_map, tag_map)
    generate_measurement_tools(tool_type_map, plugin_format_map, tag_map)
    generate_reference_tools(tool_type_map, plugin_format_map, tag_map)
    generate_composition_tools(tool_type_map, plugin_format_map, tag_map)
    generate_admin_tools(tool_type_map, plugin_format_map, tag_map)
    generate_effects(tool_type_map, effect_type_map, plugin_format_map, tag_map)
    generate_instruments(instrument_type_map, tool_type_map, plugin_format_map, tag_map)
    generate_libraries(tag_map)

    print("\n" + "=" * 60)
    print("  Seed files written to sql/seeds/")
    print("=" * 60)


if __name__ == "__main__":
    main()
