-- =============================================================================
-- Seed: entity_types
-- Generated by generate_seeds.py — do not edit directly
-- Edit csv/entity_types.csv instead
-- =============================================================================

INSERT INTO entity_types (type_id, type_name, type_description) VALUES ('932ccc99-8cc7-46cc-9ead-2c1b02a29fdc', 'Manufacturer', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO entity_types (type_id, type_name, type_description) VALUES ('8b85d508-5d04-4330-ada3-6c76c28a439a', 'Studio', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO entity_types (type_id, type_name, type_description) VALUES ('e4e51eaa-09ec-44ca-b229-1f493daba21c', 'Individual', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
