-- =============================================================================
-- Seed: tool_types
-- Generated by generate_seeds.py — do not edit directly
-- Edit csv/tool_types.csv instead
-- =============================================================================

INSERT INTO tool_types (type_id, type_name, type_description) VALUES ('a8ac45ea-f247-4291-9c1f-d44a83ebe879', 'Standalone', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO tool_types (type_id, type_name, type_description) VALUES ('9ec0a8d8-6041-4c26-a529-e65e539ce6cc', 'Plugin', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO tool_types (type_id, type_name, type_description) VALUES ('9a017254-ff50-4996-ae9d-1a9dffa46ea8', 'Embedded', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
