-- =============================================================================
-- Seed: plugin_formats
-- Generated by generate_seeds.py — do not edit directly
-- Edit csv/plugin_formats.csv instead
-- =============================================================================

INSERT INTO plugin_formats (type_id, type_name, type_description) VALUES ('aacadf18-dd64-48cb-afc1-b20719b3c8b0', 'AU', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO plugin_formats (type_id, type_name, type_description) VALUES ('f6e2b524-87b9-4f53-8e7d-7770eb2c930e', 'VST3', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO plugin_formats (type_id, type_name, type_description) VALUES ('72afadf0-67dd-4eed-bb01-71f102fcee4b', 'VST', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO plugin_formats (type_id, type_name, type_description) VALUES ('57668a87-ff53-4391-b3a7-af556b0a0874', 'UAD-2', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO plugin_formats (type_id, type_name, type_description) VALUES ('a4c6d253-5a21-4d5c-bcfa-f216f565a9d9', 'UADx', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
