-- =============================================================================
-- Seed: effect_types
-- Generated by generate_seeds.py — do not edit directly
-- Edit csv/effect_types.csv instead
-- =============================================================================

INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('c6c15978-8ef3-403f-b423-61a7dd6f93f3', 'Cabinet', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('1024edc4-200a-4b0e-a397-9a1727d058ca', 'Combo', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('b0f507f9-572d-45ab-b071-bae45bd727ba', 'Container', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('f5405897-d629-48c7-9b4a-b39662df0729', 'Delay', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('3725530a-5527-4375-8ca7-f07681f70955', 'Dynamics', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('0b32f6b8-e0ac-4acc-85ee-2d845e3de8f8', 'EQ', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('f1f50255-a7a5-4dde-af51-017fcfa3a69f', 'Harmonic Coloration', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('2eee896b-77f2-40b4-a417-c96f406b60d5', 'Head', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('893f3f4a-2348-4c5a-93ef-9685a0031971', 'Microphone', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('d7bde8b8-1be0-45f8-b6ec-81a5ba6d9fb7', 'Modulation', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('155a4766-53bf-49dd-9dd8-0de003628dd4', 'Pitch Tools', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('33f20130-b55f-48b7-bd61-b703fd45bf99', 'Preamp', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('52f8bc07-bb76-4db5-b02d-04ce771feb1f', 'DI', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('8e3c48fd-ad1a-4e91-a5dc-0eb83f0b8605', 'Reverb&Room', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('6c695d5a-5eb1-4e2c-820c-b10fb056206e', 'Spatial Processing', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO effect_types (type_id, type_name, type_description) VALUES ('bcb6f6dc-8aaa-429f-8f5b-1050ad33b119', 'Time/Phase', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
