-- =============================================================================
-- Seed: instrument_types
-- Generated by generate_seeds.py — do not edit directly
-- Edit csv/instrument_types.csv instead
-- =============================================================================

INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('bb9c3c39-21e7-4215-ac7b-3d51bd9298c0', 'Bass', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('a1e637bb-7623-4816-99e2-c893300fe973', 'Brass', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('94da235d-a650-4eeb-8ec2-abbb6e54c297', 'Container', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('708c24f3-8642-4640-b883-14842c8a95b7', 'Drums & Percussion', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('c1b69a68-ae98-4cb8-b9e3-201cb6a1897d', 'Guitars', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('5cd8803d-238f-4a25-9bec-a23110daa266', 'Keyboards', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('4065c36a-3ba8-4f21-8d45-374eda73f082', 'Pads & Textures', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('5febd22b-6c44-4c6c-901c-03f50120ae44', 'Pipes', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('55150efd-990c-4a4f-8954-5670a5fd58b7', 'Rhythm', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('188aa443-4d57-463d-a788-f5e02ab3cf39', 'Sampling', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('c04a387a-5e78-4d9d-80fe-526d460afb0b', 'Sound Design', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('9d8b351c-ad6f-4c80-9d70-9d2dfba7a804', 'Strings', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('1c9f1563-f53d-4c30-8b15-1ed04ab4b85f', 'Synth', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('7ebde8a2-9ba8-4b19-b66d-390b993a876a', 'Vocal', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('074bf968-3325-484c-94bf-2604b0b0ead0', 'Woodwinds', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
INSERT INTO instrument_types (type_id, type_name, type_description) VALUES ('d2ba6e9f-1673-489d-a70b-f1f5f1a73a76', 'World Instruments', NULL) ON CONFLICT (type_id) DO UPDATE SET type_name = EXCLUDED.type_name, type_description = EXCLUDED.type_description;
